//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public enum Talker { NPC = 0, Player = 1, Boss = 2, Other = 3 };
[System.Serializable]	
public class TalkLine
		{
		public Talker thingTalking;
		public string Sentence;
		}


